import './globals.css'
import styles from './page.module.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ja">
			<link rel="icon" href="/logo.png" />

			<body className={inter.className}>
				<header>
					<Link href="/">
						<img
							className={styles.logo}
							src="/logo-bold.png"
							alt="Atsuo Coder"
							width={256}
							height={39}
						/>
					</Link>
					<details>
						<summary>
							<h2>-&gt; Menu</h2>
						</summary>
						<a href="/contests">Contests</a>
					</details>
				</header>

				<main className={styles.main}>
					<div className={styles.center}>
					</div>
					{children}
				</main>
			</body>
		</html>
	)
}
